name: Pre-release Package

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
      - uses: pnpm/action-setup@v4
        with:
          version: latest
      - name: Install dependencies
        run: pnpm install
      - name: Update version with commit SHA
        run: |
          PACKAGE_VERSION=$(node -p "require('./package.json').version")
          COMMIT_SHA=$(git rev-parse --short HEAD)
          NEW_VERSION="${PACKAGE_VERSION}-${COMMIT_SHA}"
          npm version --no-git-tag-version "${NEW_VERSION}"
          echo "Package version updated to ${NEW_VERSION}"
      - name: Create npm package
        run: pnpm pack
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: argocd-mcp-server-package
          path: argocd-mcp-server-*.tgz
          retention-days: 7
